name: Build images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os: [bookworm, noble]
    env:
      LATEST_OS: bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Volta version
        id: volta
        run: echo "VOLTA_VERSION=$(head -n 1 latest.txt)" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.actor}}/volta
          tags: |
            type=raw,value=latest,enable=${{ matrix.os == env.LATEST_OS }}
            type=raw,value=${{ steps.volta.outputs.VOLTA_VERSION }},enable=${{ matrix.os == env.LATEST_OS }}
            type=raw,value=${{ steps.volta.outputs.VOLTA_VERSION }}-${{ matrix.os }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VOLTA_VERSION=${{ steps.volta.outputs.VOLTA_VERSION }}
            BUILDPACK=${{ matrix.os }}
