name: Build images

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        version: [2.0.0, 1.1.1]
        os: [noble, bookworm]
    
    name: Build docker image for ${{ matrix.version }}-${{ matrix.os }}
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate Docker tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{github.actor}}/volta
        tags: |
            type=raw,value=${{ matrix.version }}-${{ matrix.os }}
        
    - name: Build image and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VOLTA_VERSION=${{ matrix.version }}
            BUILDPACK=${{ matrix.os }}
