name: Build images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build-all:
        description: 'Build all versions'
        type: boolean
        default: false

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      volta_latest: ${{ steps.volta_latest.outputs.latest }}
      volta_versions: ${{ inputs.build-all == true && steps.versions.outputs.versions || steps.volta_latest.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest version
        id: volta_latest
        run: |
          ./update.sh
          echo "latest=$(head -n 1 latest.txt)" >> "$GITHUB_OUTPUT"
          echo "versions=[\"$(head -n 1 latest.txt)\"]" >> "$GITHUB_OUTPUT"
      - name: Get all versions
        if: inputs.build-all == true
        id: versions
        run: |
          echo "versions=$(./releases.sh)" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      matrix:
        os: [bookworm, bullseye]
        version: ${{ fromJSON(needs.define-matrix.outputs.volta_versions) }}
    env:
      VOLTA_LATEST: ${{ needs.define-matrix.outputs.volta_latest }}
      DEBIAN_LATEST: bookworm
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.actor}}/volta
          tags: |
            type=raw,value=latest,enable=${{ matrix.os == env.DEBIAN_LATEST }}
            type=raw,value=${{ matrix.version }},enable=${{ matrix.os == env.DEBIAN_LATEST }}
            type=raw,value=${{ matrix.version }}-${{ matrix.os }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push (default)
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VOLTA_VERSION=${{ matrix.version }}
            DEBIAN_VERSION=${{ matrix.os }}
      
      - name: Build image and push (slim)
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.slim
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VOLTA_VERSION=${{ matrix.version }}
            DEBIAN_VERSION=${{ matrix.os }}
